### ISSUE TITLE
Please add links to your Github Pages file.

### ISSUE THREAD

**Issue by ChristerNilsson** [AaaaT/hyf-html-css#1]
Example: https://christernilsson.github.io/Lab

This will make it very easy to see your .html files rendered.

**Comment by annagabain** [comment]
working on it:
https://aaaat.github.io/hyf-html-css/

**Comment by AaaaT** [comment]
My link points to my Github repository instead of displaying the html page. 
https://github.com/AaaaT/hyf-html-css/blob/master/Week1/index.html

How can I fix it?

**Comment by ChristerNilsson** [comment]
Week 1 is perfect.
The other three links should point to rendered versions, like week 1, when you have finished them.
The code is easy to find, so you do not need to point at the source. If you insist, make a 2x4 table with headers.
